[Definition]
actionstart =
actionstop =
actioncheck =
actionban =  /root/.local/bin/uvx smoloki -b http://10.1.0.254:3100 '{"job":"test","level":"Info", "host":"debian"}' '{"message":"<ip> has been banned"}'
actionunban = /root/.local/bin/uvx smoloki -b http://10.1.0.254:3100 '{"job":"test","level":"Info", "host":"debian"}' '{"message":"<ip> has been unbanned"}'
