[INPUT]
    Name              tail
    Path              /root/file.txt
    Tag               ciao.file
    DB                /var/lib/fluent-bit/ciao.db
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    storage.type      filesystem
    Refresh_Interval  1
    Read_From_Head    On
[OUTPUT]
Name          loki
Match         ciao.file
Host          10.1.0.254
Port          3100
Labels        job=ciao,env=lab,host=debian
Line_Format   json